name: Build

on: push

env:
  VER: v0.0.${{ github.run_number }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Cache permissions
        run: |
          sudo chown $(id -un) /var/cache/apt/archives
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives/*.deb
          key: apt-cache-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            apt-cache-
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
              git build-essential binutils lintian debhelper \
              dh-make devscripts libsqlite3-dev libglib2.0-dev 
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: duperemovelrd-${{ env.VER }}
      - name: DH make
        run: |
             cd duperemovelrd-${{ env.VER }}
             dh_make -y -s --createorig
      - name: Build package
        run: |
             cd duperemovelrd-${{ env.VER }}
             PREFIX=/ dpkg-buildpackage
      - name: Check outputs
        run: |
                ls
                pwd
                df
                dpkg -c duperemove-lrd_${{ env.VER }}-1_amd64.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with: 
          files: |
             duperemove-lrd_${{ env.VER }}-1_amd64.deb
      - name: Install
        run: |
                sudo dpkg --install duperemove-lrd_${{ env.VER }}-1_amd64.deb
      - name: Test run
        run: |
                duperemove --help


